services:
  face-verification:
    build: .
    container_name: face-verification-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - THRESHOLD=0.6
      - NODE_OPTIONS=--max-old-space-size=2048
    volumes:
      - ./models:/app/models:ro
      - ./test_images:/app/test_images:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
