services:
  face-verification:
    build: .
    container_name: face-verification-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - THRESHOLD=0.6
    volumes:
      - ./models:/app/models:ro
